<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!--To use most modern C# compiler features. -->
    <!--Delete after .NET 11 GA.-->
    <LangVersion>preview</LangVersion>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PacktLibraryModern\PacktLibraryModern.csproj" />
    <ProjectReference Include="..\PacktLibraryNet2\PacktLibraryNet2.csproj" />
  </ItemGroup>

  <ItemGroup Label="To simplify use of Console members.">
    <Using Include="System.Console" Static="true" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dumpify" Version="0.6.6" />
  </ItemGroup>

</Project>
