<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InterceptorsNamespaces>
      $(InterceptorsNamespaces);Microsoft.AspNetCore.Http.Validation.Generated
    </InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup Label="Package reference versions are set at the solution level.">
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <!-- Temporarily added to remove warning about Microsoft.OpenApi:
		Package 'Microsoft.OpenApi' 3.3.1 has a known high severity vulnerability, https://github.com/advisories/GHSA-v5pm-xwqc-g5wc-->
		<PackageReference Include="Microsoft.OpenApi" VersionOverride="3.8.0" />
	</ItemGroup>

  <ItemGroup Label="To simplify use of Console members.">
    <Using Include="System.Console" Static="true" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Northwind.DataContext\Northwind.DataContext.csproj" />
  </ItemGroup>

</Project>
