<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    
    <!-- Delete after .NET 11 GA.-->
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup Label="To simplify use of Console members.">
    <Using Include="System.Console" Static="true" />
  </ItemGroup>

</Project>
