<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup Label="Package reference versions are set at the solution level.">
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>

  <ItemGroup Label="Project references.">
		<!-- Folder structure:
		
		     WebData
		       Northwind.Blazor
					   Northwind.Blazor
					   Northwind.Blazor.Client
					 Northwind.Blazor.Services
					 Northwind.DataContext-->
		
    <ProjectReference Include="..\..\Northwind.Blazor.Services\Northwind.Blazor.Services.csproj" />
    <ProjectReference Include="..\Northwind.Blazor.Client\Northwind.Blazor.Client.csproj" />
		<ProjectReference Include="..\..\Northwind.DataContext\Northwind.DataContext.csproj" />
	</ItemGroup>

	<ItemGroup>
    <Using Include="Northwind.EntityModels" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Components\Pages\Functions.razor">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

</Project>
